### ISSUE TITLE
Aggiungere per ogni algoritmo delle misure di "efficienza" (tempo/memoria?)

### ISSUE THREAD

**Issue by fdila** [iralabdisco/neural_registration_comparison#28]
Da capire:

1. Cosa misurare.
2. Come misurare.

Per i tempi non dovremmo avere troppissimi problemi, ma per fare avere delle misure sensate dovremmo avere il server solo per noi quando facciamo i test, altrimenti ci va di mezzo tutta la latenza aggiunta da altre persone che lavorano su i7g4.

Per la memoria avevamo guardato in passato e ricordo che avevamo avuto problemi nel trovare un metodo che funzionasse a prescindere dalla libreria di deep learning utilizzata. È da capire.

**Comment by simone-fontana** [comment]
Per quanto riguarda l'uso esclusivo di i7, ci penso io. Oggi parlo con Sorrenti.
Per la maggior parte degli approcci dovremmo separare i tempi dei vari step. Ad esempio, 3DSmoothNet ha i tempi per la voxelizzazione, quelli per estrarre le feature e quelli per allinearli (con RANSA, FastGlobal e TEASER).

Per quanto riguarda la memoria, userei come indicatore il numero di parametri del modello.

**Comment by simone-fontana** [comment]
Aggiungi nel Wiki una pagina dove spieghi come misuri il tutto e il formato dei file in cui salvi i dati dei tempi

**Comment by fdila** [comment]
> Per quanto riguarda la memoria, userei come indicatore il numero di parametri del modello.

Non ho capito

**Comment by fdila** [comment]
Una soluzione (vagamente brutale) per la memoria è monitorarne costantemente l'utilizzo con nvidia-smi, redirezionare l'output su un file csv e calcolarci media/varianza/max (da decidere) per ogni sequenza.

```
nvidia-smi --query-gpu=timestamp,memory.used -i 1 --format=csv -lms 100
```

con `-i N` gli stai dicendo di monitorare la gpu N, `-lms 100` specifica di tirare fuori le statistiche ogni 100 ms.

E in output abbiamo:

```
timestamp, memory.used [MiB]
2023/10/05 10:31:59.828, 6 MiB
2023/10/05 10:31:59.928, 6 MiB
2023/10/05 10:32:00.028, 6 MiB
2023/10/05 10:32:00.129, 6 MiB
2023/10/05 10:32:00.229, 6 MiB
2023/10/05 10:32:00.329, 6 MiB
2023/10/05 10:32:00.429, 6 MiB
2023/10/05 10:32:00.529, 6 MiB
```

**Comment by simone-fontana** [comment]
Va bene

**Comment by fdila** [comment]
Per quanto riguarda il tempo, fare un banale `time esperimenti.sh`, guardare il tempo finale e dividere per numero esperimenti? Non è il massimo, ma ci evita di dover andare a toccare il codice di ogni esperimento.
Facendo così ci va di mezzo anche il tempo per caricare pc/salvare risultati, ma se si usa solo come comparazione tra i vari algoritmi e non come tempo assoluto dovrebbe essere ok.

**Comment by simone-fontana** [comment]
Va bene, tanto alla fine riportiamo comunque il tempo medio, non i singoli.

**Comment by fdila** [comment]
Ho messo qui (https://github.com/iralabdisco/neural_registration_comparison/wiki/Time-and-Memory-performances)  la spiegazione delle due misure.

**Comment by fdila** [comment]
Ho aggiunto nella cartella utilities gli script per guardare tempo/memoria

**Comment by fdila** [comment]
(parentesi piccolissima, i creatori di GNU parallel [tool che sto usando per far le misure di performance] chiedono di essere citati se il tool viene usato per cose scientifiche):

When using programs that use GNU Parallel to process data for publication
please cite:

  O. Tange (2011): GNU Parallel - The Command-Line Power Tool,
  ;login: The USENIX Magazine, February 2011:42-47.

This helps funding further development; AND IT WON'T COST YOU A CENT.
If you pay 10000 EUR you should feel free to use GNU Parallel without citing.

**Comment by fdila** [comment]
@simone-fontana se mi confermi che per te questo tipo di misure (https://github.com/iralabdisco/neural_registration_comparison/wiki/Time-and-Memory-performances) va bene chiudo.
