### ISSUE TITLE
Test di GeoTransformer

### ISSUE THREAD

**Issue by fdila** [iralabdisco/neural_registration_comparison#29]
Reviewer 2 ci ha chiesto esplicitamente di testarlo.

Codice e pesi sembrano essere disponibili: https://github.com/qinzheng93/GeoTransformer

**Comment by fdila** [comment]
La demo con la rete pretrainata funziona.

**Comment by fdila** [comment]
Correzione: la demo con la rete trainata su 3DMatch funziona, per usare la rete trainata su KITTI è più complicato.

**Comment by fdila** [comment]
Testando il modello trainato su 3DMatch (su pointcloud circa simili, quelle del TUM), va out of memory.
La risposta degli autori è "hai troppa poca memoria": https://github.com/qinzheng93/GeoTransformer/issues/1

**Comment by simone-fontana** [comment]
Possiamo anche decidere di escluderlo, proprio perché va out of memory. D'altro canto abbiamo già escluso un'altra rete per lo stesso motivo. Cerca di capire per quali dimensioni della point cloud va out of memory, in modo da poter eventualmente affermare che sia proprio inutilizzabili con point clouds di dimensioni decenti.

**Comment by fdila** [comment]
Sono riuscita a far funzionare la rete, sia quella trainata su 3dmatch che quella trainata su kitti.
Quella su 3dmatch funziona abbastanza sui dataset del TUM, anche se a volte va OOM, su tutti gli altri va direttamente OOM, probabilmente l'estensione spaziale degli altri dataset è troppo grande. 
Quella trainata su KITTI invece funziona abbastanza sui dataset di ETH e su p2at_met, va OOM quasi mai (forse un paio di volte sul kaist). Sui dataset del TUM invece dà errore a runtime, e se ho capito il codice è perchè con downsampling a 0.3m non riesce a trovare feature per poi fare matching.
Ho aggiunto ai file dei risultati una colonna "status", così per ogni problema sappiamo se la rete ha dato un output, se è andata OOM o se ha dato errore a runtime. Ora sto aggiornando il file che fa le statistiche sui risultati per gestire questa colonna.
Nella cartella risultati di geotransformer ci sono anche i file di tempi e misura memoria ram, ora faccio una miniguida su come sto gestendo le due misure.

**Comment by fdila** [comment]
Ho fixato un piccolo bug che gli faceva usare troppa memoria. Risultati finali:

![image](https://github.com/iralabdisco/neural_registration_comparison/assets/32036043/61ea7995-02e9-47f2-9575-47733028d08a)

![image](https://github.com/iralabdisco/neural_registration_comparison/assets/32036043/6d71ff9a-8512-41e9-8819-bc8a86873d77)
