### ISSUE TITLE
Downsampling e preprocessing per esperimenti nuovi

### ISSUE THREAD

**Issue by fdila** [iralabdisco/neural_registration_comparison#33]
@simone-fontana  stavo pensando per la questione di valutare i tempi, come gestiamo la fase di preprocessing (tipo il downsampling)?
Ricordo che nella versione originale avevamo fatto downsampling a 0.1 per tutte "offline", ma ad esempio il paper della rete che sto guardando ora (GeoTransformer) viene richiesto una leaf size specifica.

**Comment by simone-fontana** [comment]
Eliminerei il tempo di downsampling dal calcolo dei tempi. Eventualmente lo misuriamo una volta e lo indichiamo a parte. 
Che leaf size specifica richiede GeoTransformer?

**Comment by fdila** [comment]
Dipende dalla rete pretrainata, ne hanno una trainata su 3DMatch e leaf size 2.5cm e una  trainata su KITTI e leaf size 30cm.

**Comment by simone-fontana** [comment]
Userei 0.1 per gli altri, che ha più senso. Per GetoTransformer usiamo quello che richiede, specificando il motivo per cui sia diverso.

**Comment by simone-fontana** [comment]
1- Non capisco il problema. Noi prendiamo il tempo di downsampling totale e lo dividiamo per il numero di point cloud. Per ogni sequenza diciamo che ci vogliono in media tot secondi per fare il downsampling. Il tempo di allineamento lo indichiamo a parte per ogni algoritmo.

2- Il criterio della scelta della leaf size era: quella che funziona meglio. Non possiamo usare i parametri usati dagli autori originali per due motivi. Primo, spesso usano dei dati molto diversi dai nostri. Secondo, spesso non indicano che tipo di downsampling hanno usato.
Però appoggio l'idea di usare 0.1 per tutti e amen, togliendo quella frase che indichi.

**Comment by fdila** [comment]
1. Ok, non avevo considerato il "dividiamo per il numero di point cloud"
2. Magari provo a ridare un occhio ai paper delle 4 reti che c'erano nel paper per confermare che nel paper non è scritto il downsampling o che non è "compatibile" con i nostri dataset. Se non è indicato farei tutti gli esperimenti a 0.1 (sperando di non avere problemi di OOM o simili) e amen

**Comment by fdila** [comment]
Ho aggiunto in utilities/downsampling gli script che ho usato per il downsampling e in results/downsampling_times le sottocartelle con i tempi.

**Comment by fdila** [comment]
Per le 4 reti che avevamo già testato ho trovato questo nei rispettivi paper:

- 3DFeat-Net: usano downsampling a 0.2m per il training su Oxford e i test su Oxford e KITTI, e downsamplign a 0.1m per i test su dati ETH.

- Fully Convolutional Geometric Features: per la rete trainata su 3DMatch usano downsampling a 0.05m, per la rete trainata su KITTI riportano: "We trained FCGF on the KITTI registration dataset with various voxel-downsampling sizes."

- Feature metric registration: nel paper non scrivono nulla, ma aprendo il codice usano (quantomeno nella demo) downsampling a 0.05. Io avevo provato e andava OOM, noi avevamo fatto i test a 0.1 per questo motivo.

- 3DSmoothNet: Non parla esplicitamente di downsampling prima di dare in input alle point cloud all'algoritmo. Prima della parte di rete neurale ha tutta la sua parte di preprocessing particolare. Non so se ha più senso dargli in input le point cloud senza downsampling.

**Comment by fdila** [comment]
Stavo riguardando gli esperimenti di 3DSmoothNet. @simone-fontana avevi fatto tutta una parte di oulier removal con pcl prima di dare in input le cose a 3DSmoothNet, ti ricordi il perchè?

**Comment by fdila** [comment]
Riassunto breve dell'ultima conversazione:

- Usiamo voxel a 0.1, a meno che la rete non richieda un voxel size specific
- Se avanza tempo facciamo anche gli esperimenti con voxel consigliato dagli autori

**Comment by fdila** [comment]
Numero di pc per ogni dataset:

ETH
apartment: 45
gazebo_summer: 32
gazebo_winter: 31
hauptgebaude: 36
plain: 31
stairs: 31
wood_autumn: 32
wood_summer: 37

KAIST urban05: 7207

Planetary:
box_met: 112
p2at_met: 102
planetary_map: c'è solo un file con il tempo di downsampling della mappa

TUM:
pioneer_slam: 152
pioneer_slam3: 148
long_office_household: 164
