### ISSUE TITLE
Aggiungere scenario di test "robotico"

### ISSUE THREAD

**Issue by simone-fontana** [iralabdisco/neural_registration_comparison#39]
Scenarios should be reconstructed  that are more representative of the real application of "robotics".

**Comment by simone-fontana** [comment]
L'Idea è applicare le 3/4 reti migliori su un dataset robotic su un task tipo slam (ma senza loop closure). Facciamo poi vedere la ricostruzione della traiettoria e, eventualmente, la mappa. Facciamo vedere solo risultati qualitativi, non serve una ground truth precisa.

Possibili dataset:

- TUM RGBD dataset, pioneer_slam2
- [FORD Lidar campus dataset](https://robots.engin.umich.edu/SoftwareData/InfoFord)

**Comment by simone-fontana** [comment]
- [Oxford Robocar](https://robotcar-dataset.robots.ox.ac.uk/documentation/#d-lidar-1)

**Comment by fdila** [comment]
Facciamo su dataset TUM, pioneer_slam2.
Testiamo FPFH, 3DSmootNet, Predator, GeoTransformer. Per gli algoritmi che estraggono feature usiamo TEASER per allineare.

**Comment by fdila** [comment]
GeoTransformer va OOM su 23 coppie di pc, lo escludiamo

**Comment by fdila** [comment]
Visto che l'idea di allineare tutte le pc per fare una mappa è fallita facciamo gli esperimenti valutando l'errore di allineamento di ogni coppia, per i dataset TUM pioneer_slam e pioneer_slam3.

Risultati 3DSmoothnet:

pioneer_slam:
Median of errors: 0.06786588769423241 
 Q 075: 0.12510517192301687 
 Q 0.95: 0.5207792089393267
 
 pioneer_slam3:
 Median of errors: 0.04716472409145192 
 Q 075: 0.07279110618036025 
 Q 0.95: 0.17078200486465733

**Comment by fdila** [comment]
FPFH:

pioneer_slam:
Median of errors: 0.0872317555187154 
 Q 075: 0.16218626724581162 
 Q 0.95: 1.1733009055331487

pioneer_slam3:
Median of errors: 0.05867246349093514 
 Q 075: 0.12164031150740123 
 Q 0.95: 0.7664965485221993

**Comment by fdila** [comment]
Predator (trainata su 3DMatch):

pioneer_slam:
Median of errors: 0.054227490757524734 
 Q 075: 0.12467793427943419 
 Q 0.95: 1.1117293754563644
 
 pioneer_slam3:
 Median of errors: 0.035517845079194074 
 Q 075: 0.06293012217902659 
 Q 0.95: 0.5460218853637594

**Comment by fdila** [comment]
FCGF (trainata su 3DMatch):

pioneer_slam:
Median of errors: 0.07465325908197566 
 Q 075: 0.33356237624625223 
 Q 0.95: 1.1419426896549103

pioneer_slam3:
Median of errors: 0.05916319883916924 
 Q 075: 0.09628293148346603 
 Q 0.95: 0.6370089074218119

**Comment by fdila** [comment]
Ho avuto un flash tornando a casa, visto che sono riuscita a far andare RoReg e che sul TUM funziona bene vanno fatti anche questi bellissimi esperimenti robotici.

Risultati RoReg:

pioneer_slam:
Median of errors: 0.0466762036322955 
 Q 075: 0.10576609595899875 
 Q 0.95: 1.2687381104901942
 
 pioneer_slam3:
 Median of errors: 0.03188072248780284 
 Q 075: 0.0567494997529125 
 Q 0.95: 0.5279480104689461
